"""payment plan

Revision ID: 4a211986ff27
Revises: f223e4f6f0b1
Create Date: 2026-05-05 16:58:13.010435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4a211986ff27'
down_revision: Union[str, Sequence[str], None] = 'f223e4f6f0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('user', 'currentplan',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False,
               existing_server_default=sa.text("'Free'::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'currentplan',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'Free'::text"))
    op.drop_column('payment', 'plan')
    # ### end Alembic commands ###
