"""table column fix

Revision ID: cf8e467adc36
Revises: 4a211986ff27
Create Date: 2026-05-05 19:50:46.512110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf8e467adc36'
down_revision: Union[str, Sequence[str], None] = '4a211986ff27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('currentPlan', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('user', 'currentplan')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('currentplan', sa.VARCHAR(), server_default=sa.text("'Free'::text"), autoincrement=False, nullable=False))
    op.drop_column('user', 'currentPlan')
    # ### end Alembic commands ###
